fix: Library name fail if library does not exist (#205)
### Problem
One can easily provide incorrect library name to `--library-name`,
typoed, not leading to building with the relative path and leading to an
odd failure at the very end of the build

Example failure output for `solana-verify build --library-name
WrongName`

```bash
Finished building program
Program Solana version: v2.2.1
Error: Failed to parse output
```

### Solution
Make the logic to find the relative path strict, returning on the match.
Not allowing silently not finding a match when specified